Formatting files
* Formatting config.zsh
* Also removing hard to see colors from the prompt

diff --git a/bin/mvim b/bin/mvim
--- a/bin/mvim
+++ b/bin/mvim
@@ -15,19 +15,19 @@
 
 if [ -z "$VIM_APP_DIR" ]
 then
-    myDir="`dirname "$0"`"
-    myAppDir="$myDir/../Applications"
-    for i in ~/Applications ~/Applications/vim $myDir $myDir/vim $myAppDir $myAppDir/vim /Applications /Applications/vim /Applications/Utilities /Applications/Utilities/vim; do
-        if [ -x "$i/MacVim.app" ]; then
-            VIM_APP_DIR="$i"
-            break
-        fi
-    done
+	myDir="`dirname "$0"`"
+	myAppDir="$myDir/../Applications"
+	for i in ~/Applications ~/Applications/vim $myDir $myDir/vim $myAppDir $myAppDir/vim /Applications /Applications/vim /Applications/Utilities /Applications/Utilities/vim; do
+		if [ -x "$i/MacVim.app" ]; then
+			VIM_APP_DIR="$i"
+			break
+		fi
+	done
 fi
 if [ -z "$VIM_APP_DIR" ]
 then
-    echo "Sorry, cannot find MacVim.app.  Try setting the VIM_APP_DIR environment variable to the directory containing MacVim.app."
-    exit 1
+	echo "Sorry, cannot find MacVim.app.  Try setting the VIM_APP_DIR environment variable to the directory containing MacVim.app."
+	exit 1
 fi
 binary="$VIM_APP_DIR/MacVim.app/Contents/MacOS/Vim"
 
@@ -46,18 +46,18 @@ case "$name" in r*) opts="$opts -Z";; esac
 
 # vimdiff, view, and ex mode
 case "$name" in
-    *vim)
-        opts="$opts -p"
-        ;;
-    *vimdiff)
-        opts="$opts -dO"
-        ;;
-    *view)
-        opts="$opts -R"
-        ;;
-    *ex)
-        opts="$opts -e"
-        ;;
+	*vim)
+		opts="$opts -p"
+		;;
+	*vimdiff)
+		opts="$opts -dO"
+		;;
+	*view)
+		opts="$opts -R"
+		;;
+	*ex)
+		opts="$opts -e"
+		;;
 esac
 
 tabs=true
@@ -74,20 +74,20 @@ stdinoption=false
 # not; we work around this when this script is invoked as "gvim" or "rgview"
 # etc., but not when it is invoked as "vim -g".
 if [ "$gui" ]; then
-    # Note: this isn't perfect, because any error output goes to the
-    # terminal instead of the console log.
-    # But if you use open instead, you will need to fully qualify the
-    # path names for any filenames you specify, which is hard.
-    if $stdinoption; then
-        exec "$binary" -g -
-    else
-        if $tabs && [ `ps x|grep 'MacOS/MacVim'|grep -v grep|wc -l` = "1" ] && [[ `$binary --serverlist` = "VIM" ]]; then
-            #when using remote tabs you can't pass things like +5.
-            exec "$binary" -g $opts --remote-tab-silent ${1:+"$@"}
-        else
-            exec "$binary" -g $opts ${1:+"$@"}
-        fi
-    fi
+	# Note: this isn't perfect, because any error output goes to the
+	# terminal instead of the console log.
+	# But if you use open instead, you will need to fully qualify the
+	# path names for any filenames you specify, which is hard.
+	if $stdinoption; then
+		exec "$binary" -g -
+	else
+		if $tabs && [ `ps x|grep 'MacOS/MacVim'|grep -v grep|wc -l` = "1" ] && [[ `$binary --serverlist` = "VIM" ]]; then
+			#when using remote tabs you can't pass things like +5.
+			exec "$binary" -g $opts --remote-tab-silent ${1:+"$@"}
+		else
+			exec "$binary" -g $opts ${1:+"$@"}
+		fi
+	fi
 else
-    exec "$binary" $opts ${1:+"$@"}
+	exec "$binary" $opts ${1:+"$@"}
 fi
